version: '3'
services:
  flutter:
    build: .
    volumes:
      - .:/app
      - flutter-cache:/root/.pub-cache
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
    command: bash

volumes:
  flutter-cache: